services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whytteum
    ports:
      - "5432:5432"
    volumes:
      - whytteum-db-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d whytteum"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  whytteum-db-dev:
